# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: npm install -g pnpm@next-7
    init: pnpm install # runs during prebuild
    command: pnpm run dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3003
    onOpen: open-preview
